version: "3"

services:
  database:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: on-failure
    container_name: database
  server:
    container_name: server
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: on-failure
    volumes:
      - .:/server
    build:
      context: .
      dockerfile: ./Dockerfile
